### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by shelkem** [turtlecoin/turtlecoin.lol#10]
![screen shot 2018-02-11 at 15 21 55](https://user-images.githubusercontent.com/475944/36074379-971edbcc-0f3f-11e8-9dc6-3de5041ca6b3.png)

Chrome Version 64.0.3282.140
macOS 10.13.3

**Comment by shelkem** [comment]
Clearing the cache solved it.

**Comment by RocksteadyTC** [comment]
Thanks!
