### ISSUE TITLE
 doesnt slide or move in Safari

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtlecoin.lol#117]
![image](https://user-images.githubusercontent.com/34389545/87880596-7b6b0c80-c9b8-11ea-8c38-3d0c664e52cc.png)

**Comment by alexa-fabian** [comment]
![image](https://user-images.githubusercontent.com/45333376/87880818-ba1aba00-c9ec-11ea-91cd-7abab963d924.jpg)

**Comment by alexa-fabian** [comment]
On mobile when horizontal:
![D0179428-5734-4ED7-A7ED-6918D843B095](https://user-images.githubusercontent.com/45333376/87880872-18e03380-c9ed-11ea-83d9-68651117b342.png)
![9D7732D8-6840-4E84-8D58-3FAF49263E5C](https://user-images.githubusercontent.com/45333376/87880877-1ed61480-c9ed-11ea-81e1-08e072f82058.png)
The language dropdown messes the first tile up

**Comment by brandonlehmann** [comment]
Resolved in #118
