### ISSUE TITLE
Bug issue with homepage background map loading

### ISSUE THREAD

**Issue by rybofy** [turtlecoin/turtlecoin.lol#12]
What I get when the homepage at turtlecoin.lol loads
![capture](https://user-images.githubusercontent.com/36289891/36114655-7ce7862c-0fe5-11e8-9f8f-2ae51e63e7eb.PNG)

This is the one error, not sure if its related but its the only error thrown:

Error in event handler for (unknown): TypeError: Cannot read property 'addEventListener' of null
    at chrome-extension://cjbjepchlgclmpinlbbeinajphohgfod/javascripts/injection.js:1:43813
    at chrome-extension://cjbjepchlgclmpinlbbeinajphohgfod/javascripts/injection.js:1:44601
    at chrome-extension://cjbjepchlgclmpinlbbeinajphohgfod/javascripts/injection.js:1:44604

ScrollReveal: reveal on ".rotateBottomReveal"" failed, no elements found.
scrollreveal.min.js:1 ScrollReveal: reveal on ".rotateLeftReveal"" failed, no elements found.
scrollreveal.min.js:1 ScrollReveal: reveal on ".rotateRightReveal"" failed, no elements found.
scrollreveal.min.js:1 ScrollReveal: reveal on ".rotateTopReveal"" failed, no elements found.

**Comment by rybofy** [comment]
Issue is a non issue, created from a old JS Cache.

**Comment by RocksteadyTC** [comment]
CTRL F5 should solve this. We could solve this by using more conventional means first before a complete overhaul. IMO the complete overhaul is worth it only if it provides added extras like internationalization. https://css-tricks.com/strategies-for-cache-busting-css/
