### ISSUE TITLE
Spanish translation has a few issues

### ISSUE THREAD

**Issue by ordtrogen** [turtlecoin/turtlecoin.lol#128]
It mixes the two forms of address in Spanish: "tu" and "usted" (e.g Entérate and Haga clic)

Typo: Avitividad

and the newly added reference to the CLI wallet

Just creating this issue to get it on record and if I get the time, I'll create a PR with fixes.

**Comment by RocksteadyTC** [comment]
Thanks

**Comment by Daniel-Leedan** [comment]
Closed #129
