### ISSUE TITLE
Bust asset caches on deploy

### ISSUE THREAD

**Issue by ghost** [turtlecoin/turtlecoin.lol#13]
The last two issues were related to no asset cache busting strategy. Its kinda annoying :)

* https://github.com/turtlecoin/turtlecoin.lol/issues/10
* https://github.com/turtlecoin/turtlecoin.lol/issues/12

**Comment by ac1984** [comment]
I have a simple webpack static gen setup coming up for this project by the end of this week which should address this problem.

**Comment by RocksteadyTC** [comment]
Thanks

**Comment by RocksteadyTC** [comment]
If you're using a niche stack for static gen, please be prepared to write copious amounts of documentation for it so that others are not discouraged from collaborating.

**Comment by RocksteadyTC** [comment]
Please include i18n if at all possible. A growing demand is translations.

**Comment by ac1984** [comment]
@RocksteadyTC Re: niche stack – Yep thats the 🔑 when doing this. I've just gone with Webpack (as suggested by @BebopTC).

Re: Localization – Opened https://github.com/turtlecoin/turtlecoin.lol/issues/14 to work on it separately. We can hash out the details on that there.

**Comment by ar-x** [comment]
Closes via https://github.com/turtlecoin/turtlecoin.lol/pull/31
