### ISSUE TITLE
Localize site

### ISSUE THREAD

**Issue by ghost** [turtlecoin/turtlecoin.lol#14]

**Comment by RocksteadyTC** [comment]
I'd like to gather all the usernames of contributors who will be collaborating on translations.

**Comment by ac1984** [comment]
@RocksteadyTC Yes, just direct them here.

**Comment by therealxyc** [comment]
can help with german

**Comment by Getherer** [comment]
can help with polish

**Comment by LolzTrollz** [comment]
Can help with Czech. My name on the Discord server is _Dejf_ if you're gonna need it.

**Comment by TRTLshaglock** [comment]
German & Romanian

**Comment by adj-gh** [comment]
I can help with spanish. 
@ac1984 I know you said you don't like out of the box things but have you looked into [http://zanata.org/](Zanata?)

**Comment by ac1984** [comment]
@adj-gh No I haven't. Will take a look. Thanks!

**Comment by xhodan** [comment]
English/Russian (Russian is a bit rough)

**Comment by hurrdurrnein** [comment]
I could also help with German, mentioned this in discord on Monday

**Comment by eshoumeyko** [comment]
I could help with Russian / Ukrainian languages are my native

**Comment by shelkem** [comment]
Italian here ✋

**Comment by DomenKastner** [comment]
sLOVEnian also here. :)

**Comment by ChuckChain** [comment]
I can do French.

**Comment by ar-x** [comment]
@RocksteadyTC I think with the API docs are nearing completion soon, I might re pick this up over the weekend. I saw I https://github.com/turtlecoin/turtlecoin.lol/pull/27 and related, do a few things, but am not sure whats going on there (the revert).

**Comment by jerme404** [comment]
@ar-x it's finished, the revert was not intended.  I've been trying to find the time to fix the revert and merge my i18n code back in, but I'm in the middle of delivering a big project at work so my free time is nonexistent right now.  I'll try again to get to it this weekend.

**Comment by ar-x** [comment]
@jerme404 Thanks a ton!

**Comment by Sajo811** [comment]
I can help with hindi
