### ISSUE TITLE
Adding Google Analytics to website

### ISSUE THREAD

**Issue by rybofy** [turtlecoin/turtlecoin.lol#20]
We did a count on the top 20 coins on CMC and over 75% use Google Analytics, would like to add it to the main site. can generate the script if needed.

**Comment by Sajo811** [comment]
I have a question about this- given TurtleCoin is a privacy coin, should we use Google Analytics and try to invade the users' privacy?

**Comment by ar-x** [comment]
@Sajo811 What aspect of privacy does GA go against, can you elaborate? This is only on the website.

@rybofy Do you still want to do this one? For my own edification, can you tell me how it would help you.  I'm inclined to close this issue if we can't find some to lead this. In case, if you are still interested, just paste the GA snippet below and I'll add it in. 

I'm assuming @RocksteadyTC is ok with this.

**Comment by rybofy** [comment]
It really isn't that important to me, I thought it would be cool to see where traffic was coming from to better develop marketing strategies but if that infringes on privacy it's not that important.

**Comment by ar-x** [comment]
@rybofy I think the privacy aspect is not an issue here as the GA data is anonymized, and this is just on the website. Feel free to re-open this issue if you need it for a marketing initiative.

**Comment by ar-x** [comment]
@rybofy Also - you can find some of that info here: https://www.alexa.com/siteinfo/turtlecoin.lol

**Comment by ar-x** [comment]
Also https://www.semrush.com/info/turtlecoin.lol?db=us

**Comment by ar-x** [comment]
Didn't expect China to be up that high.
