### ISSUE TITLE
Afrikaans Page

### ISSUE THREAD

**Issue by jacojvv** [turtlecoin/turtlecoin.lol#38]
TurtleCoin is Safe needs to be (TurtleCoin is Veilig)
4. Maklik vir myne   needs to be (Maklik om the Myn)

**Comment by ar-x** [comment]
@jacojvv Re 4: I suppose you meant _Maklik om te Myn_ - from discord.

**Comment by jacojvv** [comment]
yes Correct

**Comment by jacojvv** [comment]
Another Markpartnerskap should be

Mark Vennootskappe

**Comment by jacojvv** [comment]
Nog belangstel? 
should be
Stel Jy nog Belang?

**Comment by ar-x** [comment]
@jacojvv let me know once you are finished.

**Comment by jacojvv** [comment]
ok,done for now.
I have asked in the channel that others also take a look
