### ISSUE TITLE
Is turtlecoin.com sourcing content (via an iframe) from turtlecoin.lol ok?

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin.lol#47]
I've seen someone mention that they own turtlecoin.com on discord. I'm not sure if they are OK, or unknown. This is concerning because along with all our static content, it _can_ also show the paper wallet http://turtlecoin.com/wallet.

**Comment by ar-x** [comment]
@RocksteadyTC quick question for you and others. i don't have a lot of context on turtlecoin.com

**Comment by RocksteadyTC** [comment]
bust these frames

**Comment by ar-x** [comment]
done via https://github.com/turtlecoin/paper-turtle/pull/11, https://github.com/turtlecoin/turtlecoin.lol/commit/e08261016dbe80949b3a709a9aef6fad72c7a0f6,
