### ISSUE TITLE
Add krang to the roadmap

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin.lol#63]
# ADD KRANG TO THE ROADMAP

**Comment by SoreGums** [comment]
Krang is a tool, not a fundamental part of Turtle Network, so while it is mighty helpful for TurtleCoin it isn't something that needs Turtle Network to exist.

Like Karai needs to be on the roadmap as it is a core part of Turtle Network. Once Karai is a thing, Turtle Network doesn't function fully without Karai.

Turtle Network functions fine without Krang.

**Comment by Sajo8** [comment]
I see, thanks
