### ISSUE TITLE
Mapbox Doesn't Load

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/turtlecoin.lol#67]
![image](https://user-images.githubusercontent.com/20562132/48973530-2c1bdf80-f00f-11e8-99e7-264ea53371e5.png)

It says that the API token is no longer authorized. Either the token needs updated (whomever created it) or the map needs replaced with something else.

Suggestions?

**Comment by fexra** [comment]
PR https://github.com/turtlecoin/turtlecoin.lol/pull/68
