### ISSUE TITLE
Timeline <-> roadmap

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/turtlecoin.lol#69]
# timeline
3?/2018 - Won Best Crypto Community @ Crypto Influence Awards 2018
06/2018 - Ranked #19 Developer Team, Coingecko.com
06/2018 - TurtleCoin Soft-Shell Hashing Algorithm released
10/2018 - TwitchTurtle Streamlabs integration launched
10/2018 - Proof of Synchronicity Whitepaper First Draft
10/2018 - Lite-blocks, low latency transactions released
10/2018 - TRTL added to BISQ DEX
11/2018 - TRTL Services, TurtleCoin Enterprise Services launched

# roadmap
TurtlePay
Karai Smartchain
Mobius
Golang TRTL Core Suite
C# TRTL Core Suite

**Comment by RocksteadyTC** [comment]
This is kind of what I had in mind, something like this. I'd like to carry on the tradition that future goals don't need dates.

**Comment by Watt3r** [comment]
30/5/2018 - Won Best Crypto Community @ Crypto Influence Awards 2018

**Comment by Watt3r** [comment]
24/1/2018 - First GUI wallet (source https://github.com/turtlecoin/turtle-wallet-winforms/releases/tag/1.0.6598.22109)
03/2/2018 - BTCANN (source https://bitcointalk.org/index.php?topic=2872287)
09/2/2018 - Turtle Typhoon (source https://medium.com/@turtlecoin/this-week-in-turtlecoin-feb-9-2018-c8e922ad4fc1)
04/05/2018 - Reddit tipbot (source https://discordapp.com/channels/388915017187328002/401456460397150210/431485085993140256)
11/2018 - Block 1 mil mined (source https://discordapp.com/channels/388915017187328002/401456460397150210/515645475437674507)

Cite your sources kids 😉
Getting tired, will update later

**Comment by Watt3r** [comment]
ACK! I left out zedwallet, and probably a ton of other things...

17/16/2018 - Zedwallet (source https://github.com/turtlecoin/turtlecoin/pull/297)

**Comment by Watt3r** [comment]
Things im thinking of but dont know dates:  
* Webwallet release dates (shellnet, canti, and turtlewallet.lol)    
* KRANG  
* woo-turtle?  
* discord tip bot's 1 millionth tip

**Comment by fexra** [comment]
I would like to suggest TRTL Services be described as "TurtleCoin as a Service" or simply Taas (like 
Token as a Service) instead of Enterprise Services.

- Add ZedWallet (simplewallet rewrite)
- Add the web wallets (shellnet/turtlewallet.lol)
- Don't add woo-turtle (broken/part of trtl services)
- Maybe add 1 million block / 2 mil tx passed?

**Comment by ExtraHash** [comment]
SIRS?!

**Comment by fexra** [comment]
Timeline will be implemented in the new design and replace the current road map. Feel free to carry on the discussion at turtlecoin/turtlecoin-website.
