### ISSUE TITLE
Block reward figure is outdated

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin.lol#77]
The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?

**Comment by LeoCornelius** [comment]
do the block exploreres not have a api for that?

**Comment by zpalmtree** [comment]
> > The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?
> 
> Do you want the actual block reward when the API is hit or just an average over the last say 1,000 blocks?

Whatever's easiest (I guess the former). I would imagine the difference between actual and last 1000 is also very similar.

**Comment by LeoCornelius** [comment]
> > The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?
> 
> Do you want the actual block reward when the API is hit or just an average over the last say 1,000 blocks?
personally i think calculating the average over the last x blocs would be rather complex unless you start introducing databases and php (store the block reward each block) why not just round it to the nearest figure?




> > > The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?
> > 
> > 
> > Do you want the actual block reward when the API is hit or just an average over the last say 1,000 blocks?
> 
> Whatever's easiest (I guess the former). I would imagine the difference between actual and last 1000 is also very similar.

True - the emission speed is very slow and the block rewards are decreasing on average by only a few shells per block.

**Comment by crappyrules** [comment]
Where is the apology @LeoCornelius ?  Part of my terms was to never post in turtlecoin github ever again.  Did you miss that part?

**Comment by brandonlehmann** [comment]
> > > The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?
> > 
> > 
> > Do you want the actual block reward when the API is hit or just an average over the last say 1,000 blocks?
> 
> Whatever's easiest (I guess the former). I would imagine the difference between actual and last 1000 is also very similar.

I'll set up say `/reward` to return `baseReward` out of `/block/header/top` it doesn't get any easier than that.

**Comment by brandonlehmann** [comment]
> > > > The site mentions `29000 TRTL Avg. Block Reward`. This is now closer to 28k. Do we want to update this manually, or maybe move to using an API?
> > > 
> > > 
> > > Do you want the actual block reward when the API is hit or just an average over the last say 1,000 blocks?
> > 
> > 
> > Whatever's easiest (I guess the former). I would imagine the difference between actual and last 1000 is also very similar.
> 
> I'll set up say `/reward` to return `baseReward` out of `/block/header/top` it doesn't get any easier than that.

Little late, almost forgot entirely:

* https://blockapi.turtlepay.io/reward/last - returns the last baseReward
* https://blockapi.turtlepay.io/reward/next - calculates the next baseReward (yes, I know 99% of the time they are the same value)

**Comment by fexra** [comment]
Updated, see 4798a94f91cad3baa77a38720e989f848d3444b1. Will be automated using the TurtlePay API in the redesign.
