### ISSUE TITLE
Change "TurtleCoin Wiki" to "TurtleCoin Docs"

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin.lol#79]
I've already made a pr (#78) for English, but we have to do the same for the rest of languages. At a quick glance, they all seem to be the same as in English, but I didn't want to change it when I was unsure. Should I make a PR changing "TurtleCoin Wiki" in language translations to "TurtleCoin Docs"?

**Comment by fexra** [comment]
See 4798a94f91cad3baa77a38720e989f848d3444b1
