### ISSUE TITLE
Workaround for better http headers

### ISSUE THREAD

**Issue by elkimek** [turtlecoin/turtlecoin.lol#87]
So I was looking for a way to improve our website's response headers because this (https://securityheaders.com/?q=turtlecoin.lol&followRedirects=on) doesn't look good. 

But after some research I ran into this:  https://www.rzegocki.pl/blog/custom-http-headers-with-github-pages/ - it seems GitHub Pages doesn't allow changing http headers but this seems to be a workaround.

I understand it's nothing I can fix by PR so here it comes as an issue.

Or Cloudflare workers can be used to achieve it: https://scotthelme.co.uk/security-headers-cloudflare-worker/

**Comment by SoreGums** [comment]
reading about the headers on the page with all the red - not sure it warrants maintaining an external account for an OSS project.

- 2 cents

**Comment by brandonlehmann** [comment]
Make that 4 cents.

**Comment by brandonlehmann** [comment]
Issue is stale and as stated above no way to do this without further complexity.
